version: '3.2'
services:
  etl:
    image: etl
    build:
      context: ./
      dockerfile: ./etl/Dockerfile
    environment:
      # note: a project wide env-file directive would be cleaner
      - MONGO_HOST=mongo
      - RUN_UNITTESTS_ONLY=true
    depends_on:
      - mongo

  skilloracle:
    image: skilloracle:latest
    environment:
        - API_PORT=8080
        - API_DEBUG=1
    build:
      context: ./
      dockerfile: ./skilloracle/Dockerfile
    depends_on:
        - redis
    ports:
        # see: https://github.com/docker/compose/issues/564
        # one would like to set the port to API_PORT but that doesn't 
        # look so easy...
        - "8080:8080"
    tty: true

  redis:
    image: redis

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
        - /opt/mongo_data:/data/db
